version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: privmx-qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: unless-stopped
    networks:
      - privmx-network

volumes:
  qdrant_storage:
    driver: local

networks:
  privmx-network:
    driver: bridge
