services:
  redis:
    image: redis:latest
    container_name: my-redis-instance
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data # This will persist your Redis data
    command: redis-server --appendonly yes # Enables AOF persistence

volumes:
  redis_data: # Define the named volume
