name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Run tests
        run: pnpm test -- --runInBand --ci --coverage
      - name: Build (type-check)
        run: pnpm run check-types
      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: packages/mcp-server/coverage
      - name: Generate API docs
        run: pnpm run docs:api
      - name: Upload docs
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs/api
